//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSofEng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public int lrn { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public string status { get; set; }
        public string grade_level { get; set; }
    }
}
